name: Assign issue creator

on:
  issues:
    types: [opened]   # 새 이슈가 열릴 때만 트리거

permissions:
  issues: write       # assignee를 달기 위한 권한

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue author
        uses: actions/github-script@v7
        with:
          script: |
            const creator = context.payload.issue.user.login;
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [creator]
            });
